name: testnav
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  provider: ^6.1.2
  intl: ^0.17.0

  image_picker: ^1.1.2
  http: ^1.2.2

  sliding_clipped_nav_bar: ^3.1.1
  go_router: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/loaders/
    - assets/Lottie/
    - assets/others/
    - assets/BGs/

